name: App_vendas
description: App Flutter Offline-First para cadastro de clientes
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
